SKILLS = [
  "Ruby",
  "JavaScript",
  "HTML5",
  "CSS3",
  "Ruby on Rails",
  "Node.js",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "RabbitMQ",
  "Sidekiq",
  "RESTful APIs",
  "Pub/Sub model",
  "DB schema design",
  "Unit testing with RSpec ",
  "Vue.js",
  "jQuery",
  "Bootstrap",
  "Backbone.js",
  "AG Grid",
  "Froala",
  "D3.js",
  "Responsive web design",
  "Web components using custom elements",
  "SCSS",
  "Handlebars",
  "ElasticSearch",
  "OAuth2.0",
  "Microservice and Microfrontend based architecture",
  "Git",
  "MacOS",
  "Linux",
  "Social Media Marketing",
  "SEO",
  "Google Ads",
  "Content Writing",
  "Email Marketing",
  "SMS Marketing",
  "Website Design",
  "Design Thinking",
  "Project Management",
  "Communication Skills",
  "Critical Thinking",
  "Automation Testing",
  "Selenium using IDE & Web Driver",
  "Selenium Grid",
  "Firebug & Firepath",
  "Manual Testing",
  "Expertise in Software Manual Testing Techniques",
  "Microsoft Technology",
  "Open Source Technology",
  "Eclipse",
  "TestNG",
  "Query",
  "JIRA",
  "Bugzilla",
  "Test Link",
  "Jenkins",
  "Sikuli ,Firebug",
  "POSTMAN",
  "JMeter",
  "HP QTP",
  "Oracle VM",
  "Excel Macro",
  "QC 9.0",
  "BBD Frame Work",
  "Microsoft SQL Server 2008 ",
  "SQL",
  "Core Java",
  "C",
  "Shell Scripting",
  "HTML",
  "Java Scripting",
  "Linux/Ubuntu",
  "Mac",
  "keyword research",
  "Google ads ",
  "Social media strategies",
  "Facebook & Linked in ads creation",
  "Market trend analysis",
  "E-commerce",
  "Basic Ms Word",
  "Ms-Excel",
  "Negotiation & communication skills",
  "SEO-SEM-SMO-PPC",
  "E mail marketing",
  "Google web master tools",
  "Google Analytics",
  "MS office",
  "Google Ad sense",
  "Photoshop and Editing Tools",
  "WordPress",
  "Marketing Tools",
  "Google Keyword Planner",
  "Uber suggest",
  "LSI graph",
  "SEO Profiler",
  "SEO Quake",
  "SpyfuS",
  "EM Rush",
  "Screaming Frog",
  "Moz OSE",
  "Backlink watch",
  "Buffer",
  "Hootsuit",
  "SEO Mofo",
  "Google Trends",
  "Mail chimp",
  "Adobe Photoshop",
  "Illustrator",
  "MS-Office",
  "Excel",
  "PowerPoint",
  "SQL Server2000",
  "Oracle 11g",
  "MS Access 2000",
  "SQL Developer",
  "Toad",
  "SQL Server",
  "WinSCP",
  "Informatica",
  "QR Scanner",
  "Win9xs",
  "Windows 2000 Server",
  "MS Office 2007/XP",
  "Java",
  "Charles",
  "Google Postman",
  "Voiceover",
  "CSS",
  "Javascript",
  "JSP",
  "J2EE",
  "MySQL",
  "Bootstrap",
  "JUnit",
  "Selenium Webdriver",
  "Rest API",
  "Selenium WebDriver",
  "SOAPUI",
  "GIT",
  "RESTAssured",
  "Appium",
  "Cucumber",
  "Html 5",
  "CSS 3",
  "BootStrap",
  "ReactJS",
  "Redux",
  "Webpack",
  "Maven"
]