SKILLS = [
  "Ruby",
  "JavaScript",
  "HTML5",
  "CSS3",
  "HTML",
  "CSS",
  "Ruby on Rails",
  "Node.js",
  "PostgreSQL",
  "MongoDB",
  "Redis",
  "RabbitMQ",
  "Sidekiq",
  "RESTful APIs",
  "Pub/Sub model",
  "DB schema design",
  "Unit testing with RSpec",
  "Vue.js",
  "jQuery",
  "Bootstrap",
  "Backbone.js",
  "AG Grid",
  "Froala",
  "D3.js",
  "Responsive web design",
  "Web components using custom elements",
  "SCSS",
  "Handlebars ",
  "ElasticSearch",
  "OAuth2.0",
  "Microservice",
  "Microfrontend",
  "Git",
  "MacOS",
  "Linux"
]